services:
  pr-commentator:
    build:
      context: ./
      dockerfile: Dockerfile.commentator
    image: commentator-img
    container_name: commentator
    volumes:
      - ./commentator:/go/app
    env_file:
      - ./commentator/.env
    tty: true
    stdin_open: true