services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.commentator
    image: pr-commentator-img
    container_name: pr-commentator
    volumes:
      - ./commentator:/go/app
    env_file:
      - ./commentator/.env
    tty: true
    stdin_open: true