services:
  pr-reporter:
    build:
      context: ./
      dockerfile: Dockerfile.reporter
    image: reporter-img
    container_name: reporter
    volumes:
      - ./src:/go/src
    env_file:
      - ./src/.env
    tty: true
    stdin_open: true