services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: pr-commentator-img
    container_name: pr-commentator
    volumes:
      - ./app:/go/app
    env_file:
      - .env
    tty: true
    stdin_open: true