services:
  pr-reporter:
    build:
      context: ./
      dockerfile: Dockerfile.reporter
    image: reporter-img
    container_name: reporter
    volumes:
      - .:/go/app
    env_file:
      - ./.env
    tty: true
    stdin_open: true