name: Set up Go

runs:
  steps:
    - name: Install reviewdog
      run: |
        curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

    # - name: Run golangci-lint with reviewdog (GitHub Checks)
    #   env:
    #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     golangci-lint run ./... | \
    #     reviewdog -f=golangci-lint -name="golangci-lint" -reporter=github-pr-check

    - name: Run golangci-lint with reviewdog (GitHub Checks)
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        golangci-lint run ./... | \
        reviewdog -f=golangci-lint -name="golangci-lint" -reporter=github-check

    - name: Run golangci-lint with reviewdog (GitHub PullRequest review comment)
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_PAT }}
      run: |
        golangci-lint run ./... | \
        reviewdog -f=golangci-lint -name="golangci-lint" -reporter=github-pr-review

    # - name: Run golangci-lint with reviewdog (GitHub PR Annotations)
    #   env:
    #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     golangci-lint run ./... | \
    #     reviewdog -f=golangci-lint -name="golangci-lint" -reporter=github-pr-annotations