name: Lint and Test

on:
  workflow_call: # リユーザブルワークフローとして定義
    secrets:
      REVIEWDOG_PAT:

jobs:
  go-steps:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app # appディレクトリをデフォルトの作業ディレクトリに設定

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.8'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
        env:
          GOBIN: $(go env GOPATH)/bin

      - name: Automatic Review
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/workflows/pull-request

      # - name: Install reviewdog
      #   if: ${{ github.event_name == 'pull_request' }}
      #   run: |
      #     curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

      # # - name: Run golangci-lint with reviewdog (GitHub Checks)
      # #   env:
      # #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # #   run: |
      # #     golangci-lint run ./... | \
      # #     reviewdog -f=golangci-lint -name="golangci-lint" -reporter=github-pr-check

      # - name: Run golangci-lint with reviewdog (GitHub Checks)
      #   env:
      #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     golangci-lint run ./... | \
      #     reviewdog -f=golangci-lint -name="golangci-lint" -reporter=github-check

      # - name: Run golangci-lint with reviewdog (GitHub PullRequest review comment)
      #   env:
      #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_PAT }}
      #   run: |
      #     golangci-lint run ./... | \
      #     reviewdog -f=golangci-lint -name="golangci-lint" -reporter=github-pr-review

      # # - name: Run golangci-lint with reviewdog (GitHub PR Annotations)
      # #   env:
      # #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # #   run: |
      # #     golangci-lint run ./... | \
      # #     reviewdog -f=golangci-lint -name="golangci-lint" -reporter=github-pr-annotations

      - name: Build Test
        run: go build -v ./...

      - name: Unit Test
        run: go test -v ./...
